### PR TITLE
Ignore the rest of the Chameleon snippet when it's already on the page.

### PR DESCRIPTION
**Pull request by bnorton**
Just a small change for a customer who recently turned us on via Segment (but had already integrated us directly in the past).

### CODE REVIEW

**Comment by f2prateek** [comment]
Not entirely sure what this change is, but generally we recommend people don't install a tool both outside  and within segment.

**Comment by bnorton** [comment]
@f2prateek I completely agree, however we can't always control what a user does and does not do. This is especially true when we change their user interface or present things to _their users_ -- we can't afford to get anything wrong.

The change is simply _to not_ override the actual implementation of some basic functions (identify, track, etc) when Chameleon is already on the page.

Furthermore in situations when customers will eventually install via Segment we allow them to preview Chameleon with a Chrome Extension. In the time after the snippet is enabled with Segment and when they remove the extension then we'd see problems as well.

**Comment by bnorton** [comment]
`c.root` is a reference to the "root" dom node that we add to the page when Chameleon is downloaded -- it's a simple check to see if we should proceed with adding Chameleon to the page or if we should not.

**Comment by sperand-io** [comment]
Mind rebasing? Sorry about that!

**Comment by bnorton** [comment]
@sperand-io @f2prateek rebased, tests passing and ready to go.

**Comment by bnorton** [comment]
@sperand-io ping, just bringing this back up on your list -- it's important to our customers to have this merged in. Thanks

**Comment by bnorton** [comment]
@ndhoule @sperand-io @stevenmiller888 I'm not sure what I can do to move this along -- its a small change that is currently impacting our (and your) paying customers!!

**Pull request merged**
